In [37]:
#Importing the essential library
import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt

In [38]:
#Loading the data
df=pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [39]:
new_df=df.drop('price',axis='columns')
new_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [41]:
price=df['price']
price

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [42]:
#Creaing the model
reg=linear_model.LinearRegression()
reg.fit(new_df,price)

LinearRegression()

In [44]:
#Predicting the price of plot at 3000 sq.ft
reg.predict([[3000]])

array([587979.45205479])

In [45]:
#Predicting the price of plot at 5000 sq.ft
reg.predict([[5000]])

array([859554.79452055])

In [46]:
#Applying the hypothesis of linear Regression
#Y=reg.predict*reg.coef+reg.intercept
reg.coef_

array([135.78767123])

In [47]:
reg.intercept_

180616.43835616432

In [48]:
#Loading the data whoes price is to be predicted
new_data=pd.read_csv('areas.csv')
new_data

area
0   1000
1   1500
2   2300
3   3540
4   4120
5   4560
6   5490
7   3460
8   4750
9   2300
10  9000
11  8600
12  7100

In [49]:
p=reg.predict(new_data)
p

array([ 316404.10958904,  384297.94520548,  492928.08219178,
        661304.79452055,  740061.64383562,  799808.21917808,
        926090.75342466,  650441.78082192,  825607.87671233,
        492928.08219178, 1402705.47945205, 1348390.4109589 ,
       1144708.90410959])

In [52]:
new_data['price']=p
new_data

area         price
0   1000  3.164041e+05
1   1500  3.842979e+05
2   2300  4.929281e+05
3   3540  6.613048e+05
4   4120  7.400616e+05
5   4560  7.998082e+05
6   5490  9.260908e+05
7   3460  6.504418e+05
8   4750  8.256079e+05
9   2300  4.929281e+05
10  9000  1.402705e+06
11  8600  1.348390e+06
12  7100  1.144709e+06

In [53]:
new_data.to_csv("1_Linear_Predicted_Price.csv")